In [3]:
import pandas as pd
import numpy as np

In [15]:
data=[
      ["Amine", 28, "Casablanca"],
      ["Lina", 22, "Rabat"],
      ["Youssef", 35, "Fès"],
      ["Salma", 30, "Casablanca"],
      ["Nora", np.nan, "Tanger"]
]
df = pd.DataFrame(data, columns=["Nom", "Âge", "Ville"])

In [5]:
df.head()

       Nom   Âge       Ville
0    Amine  28.0  Casablanca
1     Lina  22.0       Rabat
2  Youssef  35.0         Fès
3    Salma  30.0  Casablanca
4     Nora   NaN      Tanger

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Nom     5 non-null      str
 1   Âge     4 non-null      float64
 2   Ville   5 non-null      str
dtypes: float64(1), str(2)
memory usage: 252.0 bytes

In [7]:
df.describe()

             Âge
count   4.000000
mean   28.750000
std     5.377422
min    22.000000
25%    26.500000
50%    29.000000
75%    31.250000
max    35.000000

In [8]:
df.describe(include='all')

          Nom        Âge       Ville
count       5   4.000000           5
unique      5        NaN           4
top     Amine        NaN  Casablanca
freq        1        NaN           2
mean      NaN  28.750000         NaN
std       NaN   5.377422         NaN
min       NaN  22.000000         NaN
25%       NaN  26.500000         NaN
50%       NaN  29.000000         NaN
75%       NaN  31.250000         NaN
max       NaN  35.000000         NaN

In [9]:
# challeng2
df["Ville"]

0    Casablanca
1         Rabat
2           Fès
3    Casablanca
4        Tanger
Name: Ville, dtype: str

In [10]:
df=[df["Âge"] > 25]

In [17]:
df[df["Ville"] == "Casablanca"]

     Nom   Âge       Ville
0  Amine  28.0  Casablanca
3  Salma  30.0  Casablanca

In [18]:
df["Année de Naissance"] = 2025 - df["Âge"]

In [22]:
df["Nom"] = df["Nom"].str.upper()

In [23]:
df = df.rename(columns={"Ville": "Localisation"})

In [32]:
df

       Nom   Âge Localisation
2  YOUSSEF  35.0          Fès
3    SALMA  30.0   Casablanca
4     NORA  29.0       Tanger
1     LINA  22.0        Rabat

In [24]:
import numpy as np
df.loc[0, "Âge"] = np.nan

In [25]:
df[df.isnull().any(axis=1)]

     Nom  Âge Localisation  Année de Naissance
0  AMINE  NaN   Casablanca              1997.0
4   NORA  NaN       Tanger                 NaN

In [26]:
df["Âge"] = df["Âge"].fillna(df["Âge"].mean())

In [27]:
df = df.sort_values(by="Âge", ascending=False)

In [28]:
df = df.drop(columns=["Année de Naissance"])

In [29]:
df = df.drop(index=0)

In [31]:
df.head()

       Nom   Âge Localisation
2  YOUSSEF  35.0          Fès
3    SALMA  30.0   Casablanca
4     NORA  29.0       Tanger
1     LINA  22.0        Rabat