In [13]:
import pandas as pd
import numpy as np

In [26]:
df = pd.DataFrame({
    "Nom": ["Amine", "Lina", "Youssef", "Salma", "Nora"],
    "Âge": [28, np.nan, 35, 30, np.nan],
    "Salaire": [5000, 6000, np.nan, 5500, 5200]
})

In [27]:
df

       Nom   Âge  Salaire
0    Amine  28.0   5000.0
1     Lina   NaN   6000.0
2  Youssef  35.0      NaN
3    Salma  30.0   5500.0
4     Nora   NaN   5200.0

In [15]:
df = df.fillna(df.mean(numeric_only=True))

In [16]:
df

       Nom   Âge  Salaire
0    Amine  28.0   5000.0
1     Lina  31.0   6000.0
2  Youssef  35.0   5425.0
3    Salma  30.0   5500.0
4     Nora  31.0   5200.0

In [17]:
df = pd.DataFrame({
    "Transaction": ["T1", "T2", "T3", "T4"],
    "Montant": [500, 1500, 2500, 800]
})

In [18]:
df_filtered = df[df["Montant"] > 1000]
df_filtered

  Transaction  Montant
1          T2     1500
2          T3     2500

In [19]:
df = pd.DataFrame({
    "Région": ["Nord", "Sud", "Nord", "Sud", "Est"],
    "Ventes": [1000, 1500, 2000, 1200, 1800]
})

In [20]:
df_grouped = df.groupby("Région")["Ventes"].sum()
df_grouped

Région
Est     1800
Nord    3000
Sud     2700
Name: Ventes, dtype: int64

In [21]:
clients = pd.DataFrame({
    "customer_id": [1, 2, 3],
    "Nom": ["Amine", "Lina", "Youssef"]
})

In [22]:
commandes = pd.DataFrame({
    "customer_id": [1, 2, 1],
    "Commande": ["C1", "C2", "C3"]
})

In [29]:
df_merged = pd.merge(clients, commandes, on="customer_id", how="inner")
df_merged

   customer_id    Nom Commande
0            1  Amine       C1
1            1  Amine       C3
2            2   Lina       C2

In [30]:
df = pd.DataFrame({
    "Produit": ["A", "A", "B", "B"],
    "Région": ["Nord", "Sud", "Nord", "Sud"],
    "Ventes": [100, 150, 200, 250]
})

In [31]:
pivot = df.pivot_table(values="Ventes", index="Produit", columns="Région", aggfunc="sum")
pivot

Région   Nord  Sud
Produit
A         100  150
B         200  250